imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    templating: { engines: ['twig'] }
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: [10.0.0.0/8]
    session:         ~
    fragments:       ~
    session:
      cookie_httponly: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# mopa bootstrap Configuration
mopa_bootstrap:
    form: ~  # Adds twig form theme  support
    menu: ~  # enables twig helpers for menu

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    #use_controller: %kernel.debug%
    #bundles:        [CmfCreateBundle]
    java: %java_path%
    node: %node_path%
    filters:
        cssrewrite: ~
        less:
            node: %node_path%
            node_paths: %node_paths%
            apply_to: "\.less$"

# Doctrine Configuration
doctrine:
    dbal:
        types:
            json: Sonata\Doctrine\Types\JsonType
        default_connection:   default
        connections:
            default:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                unix_socket: %database_socket%
                dbname:   %database_name%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8
                # if using pdo_sqlite as your database driver, add the path in parameters.yml
                # e.g. database_path: %kernel.root_dir%/data/data.db3
                # path:     %database_path%
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Doctrine PHPCR-ODM configuration
doctrine_phpcr:
    session:
        backend: "%phpcr_backend%"
        workspace: "%phpcr_workspace%"
        username: "%phpcr_user%"
        password: "%phpcr_password%"
    odm:
        auto_mapping: true
        auto_generate_proxy_classes: "%kernel.debug%"

# Jackalope Metadata and Node Cache services
doctrine_cache:
    providers:
        phpcr_meta:
            type: file_system
        phpcr_nodes:
            type: file_system

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

fos_rest:
    view:
        force_redirects:
            html: true
        formats:
            json: true
            xml: true
        templating_formats:
            html: true
    allowed_methods_listener: true
    access_denied_listener:
        json: true
    format_listener:
        rules:
            - { path: ^/, priorities: [ html, json, xml, css ], fallback_format: html, prefer_extension: false }

cmf_create:
    persistence:
        phpcr:
            enabled: true
    editor_base_path: /bundles/cmfcreate/vendor/ckeditor/
    security:
        # WARNING: REMOVE THIS FOR PRODUCTION SITES
        # for demo purposes we are allowing anonymous inline editing
        role: ROLE_POWER_USER

cmf_media:
    persistence:
        phpcr:
            enabled: true

liip_imagine:
    # ...
    data_loader: cmf_media_doctrine_phpcr
    filter_sets:
        # default filter to be used with the image preview
        image_upload_thumbnail:
            quality: 85
            filters:
                thumbnail: { size: [100, 100], mode: outbound }
        image_thumbnail:
            quality: 85
            filters:
                thumbnail: { size: [200, 200], mode: inset }

fm_elfinder:
    instances:
        default:
            locale: %locale% # defaults to current request locale
            editor: ckeditor # other choices are tinymce, simple, form or custom
            fullscreen: true # defaults true, applies to simple and ckeditor editors
            include_assets: true # disable if you want to handle loading of the javascript and css assets yourself
            #compression: false # enable if you configured the uglifycss and uglifyjs2 assetic filters and want compression
            connector:
                debug: false # defaults to false
                roots:       # at least one root must be defined
                    uploads:
                        showhidden: false # defaults to false
                        driver: LocalFileSystem
                        path: uploads
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all']
                        upload_max_size: 2M

sonata_block:
    default_contexts: [cms]
    blocks:
       sonata.admin.block.admin_list:
           contexts: [admin]
       sonata.admin.block.search_result:
           contexts: [admin]
       #sonata.admin_doctrine_orm.block_audit:
       #   contexts: [admin]
       sonata.block.service.text:
       sonata.block.service.res:
       sonata.block.service.action:
       sonata.user.block.menu:
       sonata.user.block.account:
       sonata_admin_doctrine_phpcr.tree_block:
            settings:
                id: '/cms'
            contexts:   [admin]

sonata_admin:
    title: Admin Panel
    templates:
        layout: SonataAdminBundle::standard_layout.html.twig
        ajax: SonataAdminBundle:ajax_layout:html.twig
        list: SonataAdminBundle:CRUD:list.html.twig
        show: SonataAdminBundle:CRUD:show.html.twig
        edit: SonataAdminBundle:CRUD:edit.html.twig
        search: SonataAdminBundle:Core:search.html.twig
        search_result_block: SonataAdminBundle:Block:block_search_result.html.twig
    dashboard:
       block:
           - { position: left, type: sonata_admin_doctrine_phpcr.tree_block }
           - { position: right, type: sonata.admin.block.admin_list }

sonata_doctrine_phpcr_admin:
    document_tree_defaults: [locale]
    document_tree:
        Doctrine\ODM\PHPCR\Document\Generic:
            valid_children:
                - all
        Rha\ContentBundle\Document\Profile:
            valid_children: []
        Rha\ContentBundle\Document\Content:
            valid_children: []

knp_menu:
    twig:
       template: knp_menu.html.twig
    templating: false
    default_renderer: twig

    

services:
    application.twig.csrf_twig_extension:
        class: Application\GlobalBundle\Twig\CsrfTwigExtension
        arguments: ["@form.csrf_provider", "@session"]
        tags:
          - { name: twig.extension }

mobile_detect:
    redirect:
        mobile: ~
        tablet: ~
    switch_device_view: true

sensio_framework_extra:
    router:  { annotations: true }
    request: { converters: true }
