application_sonata_admin:
    resource: "@ApplicationSonataAdminBundle/Resources/config/routing.yml"
    prefix:   /

homepage:
    pattern: /
    defaults: { _controller: RhaContentBundle:Default:index }

_login_check:
    path: /login_check

_logout:
    path: /logout

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

sonata_page_cache:
    resource: '@SonataCacheBundle/Resources/config/routing/cache.xml'
    prefix: /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

rha_content:
    resource: "@RhaContentBundle/Controller/"
    type: annotation
    prefix: /

cmf_tree:
    resource: .
    type: 'cmf_tree'

create:
    resource: "@CmfCreateBundle/Resources/config/routing/rest_no_locale.xml"

cmf_create_image:
    resource: "@CmfCreateBundle/Resources/config/routing/image.xml"

cmf_media_file:
    resource: "@CmfMediaBundle/Resources/config/routing/file.xml"

cmf_media_image:
    resource: "@CmfMediaBundle/Resources/config/routing/image.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"
     
