security:

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_USER:
        ROLE_POWER_USER: [ROLE_USER]
        ROLE_ADMIN:       [ROLE_POWER_USER]
        ROLE_SONATA_ADMIN: [ROLE_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_SONATA_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        SONATA:

    providers:
        in_memory:
            memory:
                users: %security_users%


    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: _login
                check_path: _login_check
                default_target_path: /
                always_use_default_target_path: true
            logout:
                path: /logout
                target: /

    access_control:
        # admin pages
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout$,  role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # secured area
        - { path: ^/admin, roles: [ROLE_ADMIN] }
        - { path: ^/rha, roles: ROLE_POWER_USER }

        # FMElfinderBundle #change ROLE before deployment
        - { path: ^/efconnect, role: ROLE_POWER_USER }
        - { path: ^/elfinder, role: ROLE_POWER_USER }
